module.exports = {
    ChooseWorkingDirView: require('./ChooseWorkingDirView'),
    ChooseCategoryView: require('./ChooseCategoryView'),
    ChooseSceneView: require('./ChooseSceneView'),
    ChooseStepView: require('./ChooseStepView'),
    CreateNewCategoryView: require('./CreateNewCategoryView'),
    CreateNewSceneView: require('./CreateNewSceneView'),
    CreateNewStepView: require('./CreateNewStepView'),
    ShowStepMenuView: require('./ShowStepMenuView'),
    CreateTimelineDescriptionView: require('./CreateTimelineDescriptionView'),
    CreateTimelineCodeView: require('./CreateTimelineCodeView'),
    CreateTimelineCodePartialView: require('./CreateTimelineCodePartialView'),
    // CreateNewCliView: require('./CreateNewCliView'),
    EditTimelineView: require('./EditTimelineView'),
    EditTimelineCodeView: require('./EditTimelineCodeView'),
    EditTimelineDescriptionView: require('./EditTimelineDescriptionView'),
    ChoosePartialView: require('./ChoosePartialView'),
    ConfirmAddPartialView: require('./ConfirmAddPartialView'),
    ShouldIInitPlaybookView: require('./ShouldIInitPlaybookView'),
    ChooseATitleView: require('./ChooseATitleView'),
}